name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install Dependencies
        run: uv sync

      - name: Build Executable
        run: uv run pyinstaller --onefile cli.py --name yt-fetch-cli

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/yt-fetch-cli
            completions/yt-fetch-cli.bash
            completions/yt-fetch-cli.fish
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
